

INCLUDES =  -I .\\  -I..\inc\\  -I..\neowayinc\\

OBJS = example_helloWorld.o map.o app_start.o neoway_message.o neoway_analysis_sms.o smi.o fota.o user.o file_system.o



all:listobj $(OBJS)


include ..\makefiledef
